<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class AlterDepositsTableForInterestSync extends Migration
{
    public function up()
    {
        // Use DB::statement instead of ->change() to avoid doctrine/dbal requirement
        // Alter enum to varchar(255)
        DB::statement("ALTER TABLE deposits MODIFY COLUMN type VARCHAR(255) NOT NULL DEFAULT 'sukarela'");

        Schema::table('deposits', function (Blueprint $table) {
            $table->text('notes')->nullable()->after('current_balance');
            $table->boolean('is_system_generated')->default(false)->after('notes')->comment('True if generated by InterestSyncEngine');
            $table->string('period')->nullable()->after('is_system_generated')->comment('Period for bunga (YYYY-MM)');
        });
    }

    public function down()
    {
        Schema::table('deposits', function (Blueprint $table) {
            $table->dropColumn(['notes', 'is_system_generated', 'period']);
        });

        // Revert varchar to original enum
        DB::statement("ALTER TABLE deposits MODIFY COLUMN type ENUM('wajib', 'sukarela', 'pokok', 'penarikan') NOT NULL DEFAULT 'sukarela'");
    }
}
