<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AlterDepositsTableForInterestSync extends Migration
{
    public function up()
    {
        Schema::table('deposits', function (Blueprint $table) {
            $table->string('type')->change();
            $table->text('notes')->nullable()->after('current_balance');
            $table->boolean('is_system_generated')->default(false)->after('notes')->comment('True if generated by InterestSyncEngine');
            $table->string('period')->nullable()->after('is_system_generated')->comment('Period for bunga (YYYY-MM)');
        });
    }

    public function down()
    {
        Schema::table('deposits', function (Blueprint $table) {
            $table->dropColumn(['notes', 'is_system_generated', 'period']);
        });
    }
}
